data_root: '/workspace/helen/demucs_lightning'
resume_checkpoint: '/workspace/helen/demucs_lightning/outputs/2022-07-11/18-00-09/HDemucs_experiment_epoch=10_augmentation=True/version_1/checkpoints/last.ckpt'
samplerate: 44100
model: HDemucs
data_augmentation: true
segment: 11
gpus: 1
epochs: 360
seed: 42
debug: false
valid_apply: true

infer_audio_folder_path: '/workspace/helen/demucs_lightning/inf_audio'
infer_audio_ext: 'wav'
infer_segment: 11
infer_samplerate: ${samplerate}

dataloader:       
    inference:
        num_workers: 1
        
quant:  # quantization hyper params
  diffq:    # diffq penalty, typically 1e-4 or 3e-4
  qat:      # use QAT with a fixed number of bits (not as good as diffq)
  min_size: 0.2
  group_size: 8        

trainer:
  gpus: ${gpus}
  accelerator: 'ddp'
  precision: 32
  max_epochs: ${epochs}
  check_val_every_n_epoch: 1
  resume_from_checkpoint: ${resume_checkpoint}

dset:
    train:
        shift: 1
    sources: ['drums', 'bass', 'other', 'vocals']
    
augment:
  shift_same: false
  repitch:
    proba: 0.0
    max_tempo: 12
  remix:
    proba: 1
    group_size: 4
  scale:
    proba: 1
    min: 0.25
    max: 1.25
  flip: true    
    
demucs: # see demucs/demucs.py for a detailed description
  # Channels
  audio_channels: 2
  channels: 64
  growth: 2
  # Main structure
  depth: 6
  rewrite: true
  lstm_layers: 0
  # Convolutions
  kernel_size: 8
  stride: 4
  context: 1
  # Activations
  gelu: true
  glu: true
  # Normalization
  norm_groups: 4
  norm_starts: 4
  # DConv residual branch
  dconv_depth: 2
  dconv_mode: 1  # 1 = branch in encoder, 2 = in decoder, 3 = in both.
  dconv_comp: 4
  dconv_attn: 4
  dconv_lstm: 4
  dconv_init: 1e-4
  # Pre/post treatment
  resample: true
  normalize: false
  # Weight init
  rescale: 0.1

hdemucs:  # see demucs/hdemucs.py for a detailed description
  # Channels
  audio_channels: 2
  channels: 48
  channels_time:
  growth: 2
  # STFT
  nfft: 4096
  wiener_iters: 0
  end_iters: 0
  wiener_residual: false
  cac: true
  # Main structure
  depth: 6
  rewrite: true
  hybrid: true
  hybrid_old: false
  # Frequency Branch
  multi_freqs: []
  multi_freqs_depth: 3
  freq_emb: 0.2
  emb_scale: 10
  emb_smooth: true
  # Convolutions
  kernel_size: 8
  stride: 4
  time_stride: 2
  context: 1
  context_enc: 0
  # normalization
  norm_starts: 4
  norm_groups: 4
  # DConv residual branch
  dconv_mode: 1
  dconv_depth: 2
  dconv_comp: 4
  dconv_attn: 4
  dconv_lstm: 4
  dconv_init: 1e-3
  # Weight init
  rescale: 0.1
  